* Classic Shell Scripting

** Housekeeping

*** What is this project?

    This project is my attempt to document my notes as I read through the book
    Classic Shell Scripting. This book attempts to guide the reader through
    common shell scripting tasks in Bash. I thought the examples (and some of my
    own prototypes) would be good candidates for literate programming.

*** Literate programming

    Literate programming is a technique where you invert the priority of code
    and comments, writing primarily documentation explaining your thought
    process with code examples interspersed which can be combined in some way to
    produce the actual code you want. Org mode has some ability to do that
    native and I am going to use that functionality. 

    For example, if I add a script below:
    #+BEGIN_SRC shell
      echo "Hello, world!"
      echo "Literate programming is very interesting."
    #+END_SRC

    It can be executed in Spacemacs with ~<SPC> m b e~! In particular, that
    block generates this when run:
    
    #+BEGIN_EXAMPLE
    #+RESULTS:
    | Hello,   | world!      |    |      |              |
    | Literate | programming | is | very | interesting. |
    #+END_EXAMPLE
